// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnsecureWebApp.Infrastructure.Database;

namespace UnsecureWebApp.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210205195844_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UnsecureWebApp.Infrastructure.Domain.Entities.Laptops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Laptops");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Lenovo",
                            SerialNo = "C02L456987",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Dell",
                            SerialNo = "123AB458GH",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Brand = "HP",
                            SerialNo = "PO54654PUXR",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("UnsecureWebApp.Infrastructure.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "jonny@example.com",
                            HashedPassword = "password1234"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "bravo@example.com",
                            HashedPassword = "admin2020"
                        });
                });

            modelBuilder.Entity("UnsecureWebApp.Infrastructure.Domain.Entities.Laptops", b =>
                {
                    b.HasOne("UnsecureWebApp.Infrastructure.Domain.Entities.Users", "User")
                        .WithMany("Laptops")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Laptops__UserId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
